//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asha.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public string ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string PRODUCT_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public int TIME_ID { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime MODIFY_TIME { get; set; }
        public string STATUS { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SERVE_TIME SERVE_TIME { get; set; }
    }
}
